apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-apiserver
spec:
  replicas: 1
  selector:
    component: ndslabs-apiserver
  template:
    metadata:
      labels:
        component: ndslabs-apiserver
    spec:
      serviceAccountName: workbench
      volumes:
       - hostPath:
            path: "/ndslabs/data/volumes"
         name: volumes
      containers:
      - name: ndslabs-apiserver
        image: ndslabs/apiserver:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 30001
          protocol: TCP
        volumeMounts:
          - name: volumes
            mountPath: "/ndslabs/data/volumes"
        env:
          - name: VOLUME_NAME
            value: "global"
          # We can't substitute configmap values into "volumes" or "volumeMounts" above - use a sketchy sed replacement
          - name: VOLUME_PATH
            value: "/ndslabs/data/volumes"
          - name: SUPPORT_EMAIL
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: workbench.support_email
          - name: REQUIRE_APPROVAL
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: workbench.require_account_approval
          - name: DOMAIN
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: workbench.domain
          - name: SPEC_GIT_REPO
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: git.spec_repo
          - name: SPEC_GIT_BRANCH
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: git.spec_branch
          - name: SIGNIN_URL
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: workbench.signin_url
          - name: AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: workbench.auth_url
          - name: CORS_ORIGIN_ADDR
            value: "https://www.$(DOMAIN)"
          - name: ETCD_ADDR
            value: "$(NDSLABS_ETCD_SERVICE_HOST):$(NDSLABS_ETCD_SERVICE_PORT)"
          - name: KUBERNETES_ADDR
            value: "https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT_HTTPS)"
          - name: INGRESS
            value: "LoadBalancer"
          - name: SERVICE_TIMEOUT
            value: "10"
          - name: TOKEN_PATH
            value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          - name: SMTP_HOST
            value: "localhost"
          - name: SMTP_TLS
            value: "false"
      - image: namshi/smtp
        name: ndslabs-smtp
        ports:
        - containerPort: 25
          name: smtp
          protocol: TCP
        env:
          - name: MAILNAME
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.host
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.port
          - name: GMAIL_USER
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.gmail_user
          - name: GMAIL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.gmail_pass
          - name: SES_USER
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.aws_ses_user
          - name: SES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.aws_ses_password
          - name: SMARTHOST_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.smarthost_address
          - name: SMARTHOST_PORT
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.smarthost_port
          - name: SMARTHOST_USER
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.smarthost_user
          - name: SMARTHOST_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: ndslabs-config
                key: smtp.smarthost_password
