apiVersion: v1
kind: Service
metadata:
  name: ndslabs-webui
  labels:
    component: ndslabs-webui
spec:
  selector:
    component: ndslabs-webui
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-webui
spec:
  replicas: 1
  selector:
    component: ndslabs-webui
  template:
    metadata:
      labels:
        component: ndslabs-webui
    spec:
      containers:
      - name: ndslabs-webui
        image: ndslabs/angular-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: APISERVER_HOST
            value: "www.local.ndslabs.org"
          - name: APISERVER_PORT
            value: ""
          - name: APISERVER_PATH
            value: "/api"
          - name: APISERVER_SECURE
            value: "false"
          - name: ANALYTICS_ACCOUNT
            value: ""
          - name: SUPPORT_EMAIL
            value: "bodom0015@gmail.com"
          - name: GIT_DROPIN_REPO
            value: ""
          - name: GIT_DROPIN_BRANCH
            value: ""
        readinessProbe:
          httpGet:
            path: /asset/png/favicon-2-32x32.png
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 120
