apiVersion: v1
kind: Service
metadata:
  name: ndslabs-webui
  labels:
    component: ndslabs-webui
spec:
  selector:
    component: ndslabs-webui
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ndslabs-webui
spec:
  replicas: 1
  selector:
    component: ndslabs-webui
  template:
    metadata:
      labels:
        component: ndslabs-webui
    spec:
      volumes:
       - hostPath:
            path: "/home/core/ndslabs/gui/"
         name: src
      containers:
      - name: ndslabs-webui
        image: ndslabs/angular-ui:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: src
            mountPath: "/home/"
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: APISERVER_HOST
            value: "{{ APISERVER_HOST }}"
          - name: APISERVER_PORT
            value: "{{ APISERVER_PORT }}"
          - name: APISERVER_PATH
            value: "/api"
          - name: APISERVER_SECURE
            value: "{{ APISERVER_SECURE }}"
          - name: ANALYTICS_ACCOUNT
            value: ""
          - name: SUPPORT_EMAIL
            value: "{{ SUPPORT_EMAIL }}"
